spring.application.name=safetysystem

# Tomcat
server.port=8081

# Dev Tools
spring.devtools.restart.enabled=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true

# log4j2
logging.config=classpath:logger/log4j2.xml
